import { useMemo, useState, useEffect, useRef } from "react";
import { generatePack } from "../lib/pilgrimEngine.js";
import { DEMO_PLACES } from "./places.js";
import { getCurrentCoords, resolvePlace } from "./senses.js";

/* ══════════════════════════════════════════════════════════════
   BHOOMEE — one coherent app.
   Three modes (Resident · Pilgrim · Companion), all reachable from
   Home, all generated by the Pilgrim Engine. Location → engine →
   mission → capture → offering → share. No key, no backend needed.
   ══════════════════════════════════════════════════════════════ */

const C = {
  clay: "#1C1710", paper: "#F4EDE1", dawn: "#E5A15B",
  river: "#3E6B6A", moss: "#6E7A4F", ash: "#B9AE9C",
  voice: "'Fraunces', Georgia, serif", ui: "'Inter', system-ui, sans-serif",
};
const DOMAIN_TINT = { Air: "#A9B8C4", Water: C.river, Light: C.dawn, Noise: "#8C7BA0", Soil: C.moss, Waste: "#9A8468" };

const MODES = ["Resident", "Pilgrim", "Companion"];
const DEFAULT_PILGRIM = { days: 3, minutesPerDay: 30, hands_free: false };

/* One engine, three trip shapes — the mode IS the trip fed to the engine. */
function tripFor(mode, pilgrim, companionWith) {
  if (mode === "Pilgrim") return { days: pilgrim.days, minutesPerDay: pilgrim.minutesPerDay, companion: "solo", hands_free: pilgrim.hands_free };
  if (mode === "Companion") return { days: 1, minutesPerDay: 30, companion: companionWith || "with_one", hands_free: pilgrim.hands_free };
  return { days: 7, minutesPerDay: 20, companion: "solo", hands_free: false }; // Resident: slow, deep, local, ongoing
}

const SKY = {
  night: { key: "night", top: "#161a2b", mid: "#1d2338", low: "#2a3350", ground: "#1b2138", ink: "#eef0f8", sub: "#b9c0d6", celestial: "moon-stars" },
  wet: { key: "wet", top: "#9aa3a3", mid: "#aeb5b4", low: "#5f7371", ground: "#42504e", ink: "#1C1710", sub: "#4a504e", celestial: "rain" },
  dawn: { key: "dawn", top: "#e8b981", mid: "#f0cf9a", low: "#c99f63", ground: "#a97f45", ink: "#2a1c0a", sub: "#6d5636", celestial: "sun" },
  evening: { key: "evening", top: "#d99a5c", mid: "#e7b877", low: "#8f6a3c", ground: "#5c4426", ink: "#2a1c0a", sub: "#6d5636", celestial: "sun" },
  day: { key: "day", top: "#bcd0d4", mid: "#cfe0e1", low: "#6f9193", ground: "#4a6b6a", ink: "#1C1710", sub: "#4a504e", celestial: "sun" },
};
function skyKeyOf(senses) {
  const p = (senses?.daylight_phase || "").toLowerCase();
  const wet = !!senses?.wet_now || /wet|rain|monsoon|snow|drizzle/.test((senses?.weather || "").toLowerCase());
  if (/night|dark/.test(p)) return "night";
  if (wet) return "wet";
  if (/dawn|sunrise/.test(p)) return "dawn";
  if (/evening|dusk|low|golden/.test(p)) return "evening";
  return "day";
}
const skyByKey = (k) => SKY[k] || SKY.day;

function Sky({ sky }) {
  return (
    <div style={{ position: "absolute", inset: 0, overflow: "hidden" }}>
      <div style={{ position: "absolute", inset: 0, background: sky.top }} />
      <div style={{ position: "absolute", top: 0, left: 0, right: 0, height: "58%", background: sky.mid }} />
      {sky.celestial === "sun" && <div style={{ position: "absolute", top: "15%", left: "50%", transform: "translateX(-50%)", width: 92, height: 92, borderRadius: "50%", background: "rgba(251,233,196,0.92)" }} />}
      {sky.celestial === "moon-stars" && (
        <>
          {[[40, 60], [90, 120], [140, 55], [200, 100], [250, 70], [300, 130], [70, 190], [170, 150], [240, 185], [120, 220], [330, 90]].map((s, i) => (
            <div key={i} style={{ position: "absolute", left: s[0], top: s[1], width: 2, height: 2, borderRadius: "50%", background: "#e9ecf6" }} />
          ))}
          <div style={{ position: "absolute", top: 64, right: 44, width: 46, height: 46, borderRadius: "50%", background: "#cfd6ea" }} />
          <div style={{ position: "absolute", top: 58, right: 34, width: 46, height: 46, borderRadius: "50%", background: sky.top }} />
        </>
      )}
      {sky.celestial === "rain" && (
        <div style={{ position: "absolute", inset: 0 }}>
          {Array.from({ length: 26 }).map((_, i) => (
            <div key={i} style={{ position: "absolute", left: (i * 41) % 460, top: (i * 57) % 340, width: 1.4, height: 26, background: "rgba(223,227,226,0.5)", transform: "rotate(8deg)" }} />
          ))}
        </div>
      )}
      <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: "36%", background: sky.low }} />
      <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: "22%", background: sky.ground }} />
    </div>
  );
}

function Seal({ filled, of, size = 64, stroke = "#6f8b87" }) {
  const total = Math.max(1, of); const frac = Math.min(1, filled / total);
  const r = size / 2 - 3, cx = size / 2, cy = size / 2, circ = 2 * Math.PI * r;
  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
      <circle cx={cx} cy={cy} r={r} fill="none" stroke={stroke} strokeWidth="4" opacity="0.5" />
      <circle cx={cx} cy={cy} r={r} fill="none" stroke={C.dawn} strokeWidth="4" strokeLinecap="round" strokeDasharray={`${circ * frac} ${circ}`} transform={`rotate(-90 ${cx} ${cy})`} />
    </svg>
  );
}

export default function BhoomeeApp() {
  const [activePlace, setActivePlace] = useState(null);
  const [mode, setMode] = useState("Resident");
  const [pilgrim, setPilgrim] = useState(DEFAULT_PILGRIM);
  const [companionWith, setCompanionWith] = useState("with_one");
  const [companionCode, setCompanionCode] = useState(() => Math.random().toString(36).slice(2, 6).toUpperCase());
  const [view, setView] = useState("welcome");
  const [locStatus, setLocStatus] = useState("");
  const [missionIdx, setMissionIdx] = useState(0);
  const [word, setWord] = useState("");
  const [capturePhoto, setCapturePhoto] = useState(null);
  const [lastSealed, setLastSealed] = useState(null);
  const [offerings, setOfferings] = useState(() => { try { return JSON.parse(localStorage.getItem("bhoomee_offerings") || "[]"); } catch { return []; } });

  useEffect(() => {
    try { localStorage.setItem("bhoomee_offerings", JSON.stringify(offerings.map(({ photo, ...o }) => o))); } catch { /* quota */ }
  }, [offerings]);

  const trip = useMemo(() => tripFor(mode, pilgrim, companionWith), [mode, pilgrim, companionWith]);

  const pack = useMemo(() => {
    if (!activePlace) return null;
    try { return generatePack({ coords: activePlace.coords, date: new Date(), trip, body: activePlace.body, liveState: activePlace.liveState }); }
    catch { return { place_label: activePlace.label, place_kind: "unknown", senses: activePlace.liveState, missions: [] }; }
  }, [activePlace, trip]);

  const missions = pack?.missions || [];
  const sky = skyByKey(skyKeyOf(pack?.senses));
  const doneKeys = new Set(offerings.map((o) => o.key));
  const firstOpenIdx = Math.max(0, missions.findIndex((m) => !doneKeys.has(m.id + "@" + (activePlace?.id || ""))));
  const mission = missions[missionIdx] || missions[firstOpenIdx] || missions[0];

  async function useMyLocation() {
    setView("locating"); setLocStatus("Finding where you're standing…");
    try {
      const coords = await getCurrentCoords();
      setLocStatus("Reading the air, the light, the nearest water…");
      const place = await resolvePlace(coords);
      setActivePlace(place); setMissionIdx(0); setView("home");
    } catch { setLocStatus(""); setView("places"); }
  }
  function chooseDemo(id) {
    const p = DEMO_PLACES.find((x) => x.id === id) || DEMO_PLACES[0];
    setActivePlace({ ...p, live: false }); setMissionIdx(0); setView("home");
  }
  // Selecting a mode: Resident applies at once; Pilgrim/Companion open setup.
  function pickMode(m) {
    if (m === "Resident") { setMode("Resident"); setMissionIdx(0); ensurePlaceThen("home"); }
    else if (m === "Pilgrim") setView("pilgrimSetup");
    else setView("companionSetup");
  }
  function ensurePlaceThen(v) { if (activePlace) setView(v); else useMyLocation(); }
  function startPilgrim() { setMode("Pilgrim"); setMissionIdx(0); ensurePlaceThen("home"); }
  function startCompanion() { setMode("Companion"); setMissionIdx(0); ensurePlaceThen("home"); }

  function openMission(i) { setMissionIdx(i); setView("mission"); }
  function onCapture(e) {
    const file = e.target.files && e.target.files[0]; if (!file) return;
    const reader = new FileReader();
    reader.onload = () => { setCapturePhoto(reader.result); setView("offering"); };
    reader.readAsDataURL(file);
  }
  function seal() {
    if (!mission) return;
    const key = mission.id + "@" + (activePlace?.id || "");
    const off = {
      key, place: pack.place_label, placeId: activePlace?.id, domain: mission.domain,
      jane: mission.janeFraming, word: word.trim(), sky: sky.key, arc: arcStage(mission),
      tint: DOMAIN_TINT[mission.domain] || C.moss, date: new Date().toISOString().slice(0, 10),
      mode, photo: capturePhoto || null,
    };
    setOfferings((prev) => [off, ...prev.filter((o) => o.key !== key)]);
    setLastSealed(off); setWord(""); setCapturePhoto(null); setView("sealed");
  }
  async function share(off) {
    try {
      const blob = await composeCard(off);
      const file = new File([blob], "bhoomee-offering.png", { type: "image/png" });
      const caption = `${receiveLine()}${off.word ? " — " + off.word : ""}\n${off.place} · #bhoomee`;
      if (navigator.canShare && navigator.canShare({ files: [file] })) await navigator.share({ files: [file], text: caption });
      else { const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "bhoomee-offering.png"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 4000); }
    } catch { /* cancelled/unsupported */ }
  }

  return (
    <div style={{ minHeight: "100vh", background: C.paper, fontFamily: C.ui, color: C.clay }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,300;0,9..144,400;1,9..144,300&family=Inter:wght@400;500&display=swap');
        .bh-fade{animation:bhf .5s cubic-bezier(.22,.61,.36,1)}@keyframes bhf{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
        .bh-cta{background:${C.dawn};color:#2a1c0a;border:none;border-radius:999px;padding:14px 18px;font-family:${C.ui};font-weight:500;font-size:15px;width:100%;cursor:pointer;transition:transform .2s;box-sizing:border-box;text-align:center;display:block}
        .bh-cta:active{transform:scale(.98)}
        .bh-ghost{background:transparent;border:1px solid ${C.ash};color:${C.clay};border-radius:999px;padding:13px 18px;font-family:${C.ui};font-weight:500;font-size:15px;width:100%;cursor:pointer;box-sizing:border-box}
        .bh-soft{margin-top:10px;text-align:center;font-size:13px;font-style:italic;font-family:${C.voice};background:none;border:none;width:100%;cursor:pointer}
        .bh-voice{font-family:${C.voice};font-weight:300;line-height:1.24}
        .bh-k{font-size:11px;letter-spacing:.14em;text-transform:uppercase}
        input.bh-in{width:100%;box-sizing:border-box;border:1px solid ${C.ash};background:#fffdf8;border-radius:12px;padding:12px 14px;font-family:${C.voice};font-size:17px;color:${C.clay};margin-top:10px}
        input.bh-in:focus{outline:none;border-color:${C.dawn}}
      `}</style>

      <div style={{ maxWidth: 460, margin: "0 auto", position: "relative", minHeight: "100vh" }}>
        <div style={{ position: "relative", minHeight: "100vh", paddingBottom: 78 }}>
          {view === "welcome" && <Welcome onLocate={useMyLocation} onModes={() => setView("modes")} onExplore={() => setView("places")} />}
          {view === "locating" && <Locating status={locStatus} />}
          {view === "modes" && <Modes current={mode} pick={pickMode} onBack={() => setView(activePlace ? "home" : "welcome")} />}
          {view === "pilgrimSetup" && <PilgrimSetup pilgrim={pilgrim} setPilgrim={setPilgrim} onStart={startPilgrim} onBack={() => setView("modes")} />}
          {view === "companionSetup" && <CompanionSetup companionWith={companionWith} setCompanionWith={setCompanionWith} code={companionCode} onStart={startCompanion} onBack={() => setView("modes")} />}
          {view === "home" && pack && <Home pack={pack} sky={sky} mode={mode} trip={trip} mission={missions[firstOpenIdx] || missions[0]} firstOpenIdx={firstOpenIdx} total={missions.length} openMission={() => openMission(firstOpenIdx)} onSit={() => setView("sit")} pickMode={pickMode} />}
          {view === "sit" && <Sit sky={sky} onDone={() => setView("home")} placeLabel={pack?.place_label || "the world"} />}
          {view === "mission" && mission && <Mission mission={mission} sky={sky} trip={trip} mode={mode} onBack={() => setView("home")} onCapture={onCapture} filled={firstOpenIdx} />}
          {view === "offering" && mission && <Offering mission={mission} sky={sky} place={pack.place_label} photo={capturePhoto} word={word} setWord={setWord} onSeal={seal} onRetake={() => setView("mission")} />}
          {view === "sealed" && lastSealed && <Sealed off={lastSealed} onShare={() => share(lastSealed)} onDone={() => setView("atlas")} />}
          {view === "atlas" && <Atlas offerings={offerings} onShare={share} />}
          {view === "places" && <Places activeId={activePlace?.id} onLocate={useMyLocation} choose={chooseDemo} onModes={() => setView("modes")} />}
        </div>
        {view !== "welcome" && view !== "locating" && <TabBar view={view} setView={setView} hasPlace={!!activePlace} />}
      </div>
    </div>
  );
}

/* ─── WELCOME ─── */
function Welcome({ onLocate, onModes, onExplore }) {
  return (
    <div className="bh-fade" style={{ position: "relative", minHeight: "100vh" }}>
      <div style={{ position: "absolute", inset: 0 }}><Sky sky={SKY.dawn} /></div>
      <div style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", justifyContent: "flex-end", padding: 22 }}>
        <div style={{ background: "rgba(28,23,16,.5)", borderRadius: 20, padding: 20 }}>
          <div className="bh-voice" style={{ fontSize: 30, color: "#f4ede1" }}>Oh — there you are.</div>
          <div className="bh-voice" style={{ fontSize: 17, fontStyle: "italic", color: "#e9d9c2", marginTop: 8 }}>Tell me where you're standing, and I'll show you what's alive around you right now.</div>
          <button className="bh-cta" style={{ marginTop: 16 }} onClick={onLocate}>◉ Use my location</button>
          <button className="bh-ghost" style={{ marginTop: 10, color: "#f4ede1", borderColor: "rgba(255,255,255,.4)" }} onClick={onModes}>Choose a mode — Resident · Pilgrim · Companion</button>
          <button className="bh-soft" style={{ color: "#d8cbb5" }} onClick={onExplore}>or wander a place first</button>
        </div>
      </div>
    </div>
  );
}

function Locating({ status }) {
  return (
    <div className="bh-fade" style={{ position: "relative", minHeight: "100vh" }}>
      <div style={{ position: "absolute", inset: 0 }}><Sky sky={SKY.day} /></div>
      <div style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: 30 }}>
        <div style={{ width: 70, height: 70, borderRadius: "50%", border: "3px solid rgba(255,255,255,.35)", borderTopColor: "#fff", animation: "bhspin 1s linear infinite" }} />
        <style>{`@keyframes bhspin{to{transform:rotate(360deg)}}`}</style>
        <div className="bh-voice" style={{ fontSize: 20, color: "#1C1710", marginTop: 24, textAlign: "center" }}>{status || "Listening for you…"}</div>
      </div>
    </div>
  );
}

/* ─── MODES ─── */
function Modes({ current, pick, onBack }) {
  const cards = [
    { id: "Resident", line: "Slow and deep, where you live.", sub: "An ongoing portrait of your own ground, one small looking at a time." },
    { id: "Pilgrim", line: "A journey, compressed into an arc.", sub: "Declare a trip; I write the whole thing at once so it works with no signal." },
    { id: "Companion", line: "Walk it with someone.", sub: "Solo, with one, or a group — share a code and meet the same place together." },
  ];
  return (
    <div className="bh-fade" style={{ minHeight: "100vh", padding: "20px 16px 0" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
        <button onClick={onBack} style={{ background: "none", border: "none", fontSize: 22, cursor: "pointer", color: C.clay }}>←</button>
        <div className="bh-voice" style={{ fontSize: 24 }}>How will you walk?</div>
      </div>
      <div style={{ marginTop: 14 }}>
        {cards.map((c) => (
          <button key={c.id} onClick={() => pick(c.id)} style={{ display: "block", width: "100%", textAlign: "left", background: c.id === current ? "#fffdf8" : "transparent", border: `1px solid ${c.id === current ? C.dawn : C.ash}`, borderRadius: 16, padding: "15px 16px", marginBottom: 12, cursor: "pointer" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <div className="bh-voice" style={{ fontSize: 20, color: C.clay }}>{c.id}</div>
              {c.id === current && <span className="bh-k" style={{ color: "#8a5a2a" }}>current</span>}
            </div>
            <div className="bh-voice" style={{ fontSize: 16, fontStyle: "italic", color: "#6d6553", marginTop: 3 }}>{c.line}</div>
            <div style={{ fontSize: 12, color: "#8a806c", marginTop: 6 }}>{c.sub}</div>
          </button>
        ))}
      </div>
    </div>
  );
}

/* ─── PILGRIM SETUP ─── */
function PilgrimSetup({ pilgrim, setPilgrim, onStart, onBack }) {
  const set = (k, v) => setPilgrim((t) => ({ ...t, [k]: v }));
  const Opt = ({ on, children, onClick }) => (
    <button onClick={onClick} style={{ flex: 1, padding: "10px 8px", borderRadius: 12, border: `1px solid ${on ? C.dawn : C.ash}`, background: on ? "#fffdf8" : "transparent", fontFamily: C.ui, fontSize: 13, cursor: "pointer", color: C.clay }}>{children}</button>
  );
  return (
    <div className="bh-fade" style={{ minHeight: "100vh", padding: "20px 18px 0" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
        <button onClick={onBack} style={{ background: "none", border: "none", fontSize: 22, cursor: "pointer", color: C.clay }}>←</button>
        <div className="bh-voice" style={{ fontSize: 24 }}>Pilgrim mode</div>
      </div>
      <div style={{ fontSize: 13, color: "#7d7461", marginTop: 6, marginBottom: 18 }}>A compressed arc for a journey. I'll write the whole trip at once.</div>
      <div className="bh-k" style={{ color: "#7d7461" }}>How many days</div>
      <div style={{ display: "flex", gap: 8, marginTop: 8 }}>{[1, 3, 5, 7].map((d) => <Opt key={d} on={pilgrim.days === d} onClick={() => set("days", d)}>{d} day{d > 1 ? "s" : ""}</Opt>)}</div>
      <div className="bh-k" style={{ color: "#7d7461", marginTop: 18 }}>Minutes a day</div>
      <div style={{ display: "flex", gap: 8, marginTop: 8 }}>{[15, 30, 60].map((m) => <Opt key={m} on={pilgrim.minutesPerDay === m} onClick={() => set("minutesPerDay", m)}>{m} min</Opt>)}</div>
      <div className="bh-k" style={{ color: "#7d7461", marginTop: 18 }}>Capture</div>
      <div style={{ display: "flex", gap: 8, marginTop: 8 }}>
        <Opt on={!pilgrim.hands_free} onClick={() => set("hands_free", false)}>Phone camera</Opt>
        <Opt on={pilgrim.hands_free} onClick={() => set("hands_free", true)}>Camera glasses (hands-free)</Opt>
      </div>
      <button className="bh-cta" style={{ marginTop: 26 }} onClick={onStart}>Begin the pilgrimage →</button>
    </div>
  );
}

/* ─── COMPANION SETUP (handshake) ─── */
function CompanionSetup({ companionWith, setCompanionWith, code, onStart, onBack }) {
  const [joinCode, setJoinCode] = useState("");
  const Opt = ({ on, children, onClick }) => (
    <button onClick={onClick} style={{ flex: 1, padding: "10px 8px", borderRadius: 12, border: `1px solid ${on ? C.dawn : C.ash}`, background: on ? "#fffdf8" : "transparent", fontFamily: C.ui, fontSize: 13, cursor: "pointer", color: C.clay }}>{children}</button>
  );
  return (
    <div className="bh-fade" style={{ minHeight: "100vh", padding: "20px 18px 0" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
        <button onClick={onBack} style={{ background: "none", border: "none", fontSize: 22, cursor: "pointer", color: C.clay }}>←</button>
        <div className="bh-voice" style={{ fontSize: 24 }}>Companion mode</div>
      </div>
      <div style={{ fontSize: 13, color: "#7d7461", marginTop: 6, marginBottom: 18 }}>Walk the same place with someone. Missions become shared — each of you gets a part.</div>
      <div className="bh-k" style={{ color: "#7d7461" }}>Who's with you</div>
      <div style={{ display: "flex", gap: 8, marginTop: 8 }}>
        <Opt on={companionWith === "with_one"} onClick={() => setCompanionWith("with_one")}>With one</Opt>
        <Opt on={companionWith === "group"} onClick={() => setCompanionWith("group")}>A group</Opt>
      </div>
      <div style={{ marginTop: 20, background: "#fffdf8", border: `1px solid ${C.ash}`, borderRadius: 16, padding: 16 }}>
        <div className="bh-k" style={{ color: "#7d7461" }}>The handshake</div>
        <div className="bh-voice" style={{ fontSize: 16, fontStyle: "italic", color: "#6d6553", marginTop: 4 }}>Stand in the same place and share this word. You'll be given the same portrait.</div>
        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 12 }}>
          <div className="bh-voice" style={{ fontSize: 30, letterSpacing: ".18em", color: C.clay }}>{code}</div>
          <button className="bh-ghost" style={{ width: "auto", padding: "8px 14px" }} onClick={() => { try { navigator.clipboard.writeText(code); } catch (e) { /* ignore */ } }}>Copy</button>
        </div>
        <input className="bh-in" maxLength={6} value={joinCode} onChange={(e) => setJoinCode(e.target.value.toUpperCase())} placeholder="or enter their word to join" />
      </div>
      <button className="bh-cta" style={{ marginTop: 22 }} onClick={onStart}>Walk together →</button>
    </div>
  );
}

/* ─── HOME (mode switch + engine-driven ask) ─── */
function Home({ pack, sky, mode, trip, mission, firstOpenIdx, total, openMission, onSit, pickMode }) {
  const modeLabel = mode === "Pilgrim" ? `pilgrim · day 1/${trip.days}` : mode === "Companion" ? `together · ${trip.companion === "group" ? "a group" : "with one"}` : "resident";
  const ask = mission ? mission.janeFraming : null;
  return (
    <div className="bh-fade" style={{ position: "relative", minHeight: "100vh" }}>
      <div style={{ position: "absolute", inset: 0 }}><Sky sky={sky} /></div>
      <div style={{ position: "relative", padding: "18px 18px 0", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <span className="bh-voice" style={{ fontSize: 22, color: sky.ink }}>Bhoomee</span>
        <span className="bh-k" style={{ color: sky.sub }}>{pack.place_label} · {modeLabel}</span>
      </div>

      {/* three-mode switch — reachable from Home */}
      <div style={{ position: "relative", display: "flex", gap: 6, justifyContent: "center", marginTop: 12, padding: "0 16px" }}>
        {MODES.map((m) => (
          <button key={m} onClick={() => pickMode(m)} style={{ flex: 1, padding: "7px 4px", borderRadius: 999, border: `1px solid ${m === mode ? C.dawn : "rgba(255,255,255,.5)"}`, background: m === mode ? "rgba(244,237,225,.92)" : "rgba(255,255,255,.18)", color: m === mode ? "#8a5a2a" : sky.ink, fontFamily: C.ui, fontWeight: 500, fontSize: 12, cursor: "pointer" }}>{m}</button>
        ))}
      </div>

      <div style={{ position: "relative", display: "flex", gap: 8, justifyContent: "center", marginTop: 14 }}>
        {["Air", "Water", "Light", "Noise", "Soil", "Waste"].map((d) => {
          const calls = pack.missions?.some((m) => m.domain === d);
          return <span key={d} title={d} style={{ width: 10, height: 10, borderRadius: "50%", background: DOMAIN_TINT[d], opacity: calls ? 1 : 0.35, boxShadow: calls ? `0 0 0 3px ${DOMAIN_TINT[d]}44` : "none" }} />;
        })}
      </div>

      <div style={{ position: "absolute", left: 14, right: 14, bottom: 16 }}>
        <div style={{ background: sky.key === "night" ? "rgba(22,26,43,.66)" : "rgba(244,237,225,.94)", borderRadius: 18, padding: "16px 16px 15px" }}>
          <div className="bh-k" style={{ color: sky.key === "night" ? "#b9c0d6" : "#7d7461" }}>Mother asks of you, now</div>
          <div className="bh-voice" style={{ fontSize: 21, marginTop: 7, color: sky.key === "night" ? sky.ink : C.clay }}>{ask ? shorten(ask) : "Just be here with me a moment."}</div>
          {mission && (
            <div style={{ display: "flex", gap: 8, marginTop: 11 }}>
              <Pill>{mission.domain} · {mission.timeBudgetMin} min</Pill>
              <Pill dim>mission {firstOpenIdx + 1} of {total}</Pill>
            </div>
          )}
          <button className="bh-cta" style={{ marginTop: 13 }} onClick={openMission}>{mission ? "Begin" : "Choose a mode"}</button>
          <button className="bh-soft" style={{ color: sky.key === "night" ? "#9aa2bd" : "#8a806c" }} onClick={onSit}>or just sit with me a minute</button>
        </div>
      </div>
    </div>
  );
}

function Sit({ sky, onDone, placeLabel }) {
  const [count, setCount] = useState(0);
  useEffect(() => {
    if (count >= 5) { const t = setTimeout(onDone, 1200); return () => clearTimeout(t); }
    const t = setTimeout(() => setCount((c) => c + 1), 3000); return () => clearTimeout(t);
  }, [count, onDone]);
  return (
    <div className="bh-fade" style={{ position: "relative", minHeight: "100vh" }}>
      <div style={{ position: "absolute", inset: 0 }}><Sky sky={sky} /></div>
      <div style={{ position: "absolute", inset: 0, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: 30 }}>
        <div style={{ width: 120, height: 120, borderRadius: "50%", background: "rgba(255,255,255,.18)", border: "1px solid rgba(255,255,255,.35)", transform: `scale(${1 + Math.sin(count) * 0.06})`, transition: "transform 3s ease-in-out" }} />
        <div className="bh-voice" style={{ fontSize: 22, color: sky.ink, marginTop: 26, textAlign: "center" }}>{count >= 5 ? "Good. I'm always here." : `Breathe with ${placeLabel}. Nothing is being asked of you.`}</div>
      </div>
    </div>
  );
}

/* ─── MISSION (capture here; shows shared part in Companion) ─── */
function Mission({ mission, sky, trip, mode, onBack, onCapture, filled }) {
  return (
    <div className="bh-fade" style={{ position: "relative", minHeight: "100vh" }}>
      <div style={{ position: "absolute", inset: 0 }}><Sky sky={sky} /></div>
      <div style={{ position: "relative", padding: "18px 16px 0", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <button onClick={onBack} style={{ background: "none", border: "none", color: sky.ink, fontSize: 22, cursor: "pointer" }}>←</button>
        <span className="bh-k" style={{ color: sky.sub }}>{mission.domain} portrait</span>
        <span style={{ width: 20 }} />
      </div>
      <div style={{ position: "relative", display: "flex", justifyContent: "center", marginTop: 26 }}><Seal filled={filled} of={4} size={64} /></div>
      <div style={{ position: "absolute", left: 14, right: 14, bottom: 16 }}>
        <div style={{ background: "rgba(244,237,225,.95)", borderRadius: 18, padding: 16 }}>
          <div className="bh-k" style={{ color: "#7d7461" }}>{arcStage(mission)} · your task</div>
          <div className="bh-voice" style={{ fontSize: 19, marginTop: 6 }}>{mission.task}</div>
          {mode === "Companion" && mission.companionRendered && (
            <div className="bh-voice" style={{ fontSize: 15, color: "#8a5a2a", marginTop: 8 }}>Together: {mission.companionRendered}</div>
          )}
          <div className="bh-voice" style={{ fontSize: 14, fontStyle: "italic", color: "#6d6553", marginTop: 9 }}>“{mission.janeFraming}” — Mother</div>
          <label className="bh-cta" style={{ marginTop: 13 }}>
            {trip.hands_free ? "＋ Add your glasses photo" : "◎ Capture the offering"}
            <input type="file" accept="image/*" style={{ display: "none" }} onChange={onCapture} />
          </label>
        </div>
      </div>
    </div>
  );
}

/* ─── OFFERING (preview + one true word) ─── */
function Offering({ mission, sky, place, photo, word, setWord, onSeal, onRetake }) {
  return (
    <div className="bh-fade" style={{ minHeight: "100vh", background: "#efe7d9" }}>
      <div style={{ padding: "18px 16px 0", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <button onClick={onRetake} style={{ background: "none", border: "none", fontSize: 22, cursor: "pointer", color: C.clay }}>←</button>
        <span className="bh-k" style={{ color: "#8a806c" }}>Seal your offering</span>
        <span style={{ width: 20 }} />
      </div>
      <div style={{ display: "flex", justifyContent: "center", marginTop: 14 }}>
        <OfferingCard off={{ word, domain: mission.domain, arc: arcStage(mission), place, date: new Date().toISOString().slice(0, 10), tint: DOMAIN_TINT[mission.domain], sky: sky.key }} photo={photo} />
      </div>
      <div style={{ padding: "16px 22px 0" }}>
        <div className="bh-k" style={{ color: "#8a806c" }}>Add one true word of your own</div>
        <input className="bh-in" maxLength={40} value={word} onChange={(e) => setWord(e.target.value)} placeholder="what did it feel like?" />
        <button className="bh-cta" style={{ marginTop: 14 }} onClick={onSeal}>Seal into the Atlas</button>
      </div>
    </div>
  );
}

/* ─── SEALED (share) ─── */
function Sealed({ off, onShare, onDone }) {
  return (
    <div className="bh-fade" style={{ minHeight: "100vh", background: "#efe7d9" }}>
      <div style={{ padding: "18px 16px 4", textAlign: "center" }} className="bh-voice">
        <div style={{ fontSize: 22, color: C.clay }}>Sealed.</div>
        <div style={{ fontSize: 14, fontStyle: "italic", color: "#6d6553" }}>Give it to the world if you like.</div>
      </div>
      <div style={{ display: "flex", justifyContent: "center", marginTop: 8 }}><OfferingCard off={off} photo={off.photo} /></div>
      <div style={{ padding: "18px 22px 0" }}>
        <button className="bh-cta" onClick={onShare}>⤴ Share this offering</button>
        <button className="bh-ghost" style={{ marginTop: 10 }} onClick={onDone}>Keep it in the Atlas</button>
      </div>
    </div>
  );
}

/* ─── the card (reused) ─── */
function OfferingCard({ off, photo }) {
  const tint = off.tint || C.moss;
  const k = off.sky || "day";
  const graded = k === "night" ? "#2a3350" : k === "wet" ? "#5f7371" : (k === "dawn" || k === "evening") ? "#c98f4e" : "#6f9193";
  return (
    <div style={{ width: 280, background: "#faf5ea", borderRadius: 8, overflow: "hidden", border: "1px solid #e4d8c2" }}>
      <div style={{ height: 224, background: graded, position: "relative", overflow: "hidden" }}>
        {photo ? <img alt="offering" src={photo} style={{ width: "100%", height: "100%", objectFit: "cover" }} /> : <div style={{ position: "absolute", top: 12, left: 12, color: "rgba(255,255,255,.8)", fontSize: 11, letterSpacing: ".1em" }}>your photo goes here</div>}
        <div style={{ position: "absolute", bottom: 0, left: 0, right: 0, height: "40%", background: "linear-gradient(rgba(0,0,0,0), rgba(0,0,0,.28))" }} />
      </div>
      <div style={{ padding: "14px 18px 17px" }}>
        <div className="bh-voice" style={{ fontSize: 19, color: "#2a1c0a", lineHeight: 1.22 }}>{receiveLine()}</div>
        {off.word ? <div className="bh-voice" style={{ fontSize: 16, fontStyle: "italic", color: tint, marginTop: 8 }}>— {off.word}</div> : null}
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 12 }}>
          <div>
            <div className="bh-k" style={{ color: "#8a5a2a", fontSize: 10 }}>◈ {off.domain} · {off.arc}</div>
            <div style={{ fontSize: 11, color: "#a89a80", marginTop: 3 }}>{off.place} · {fmtDate(off.date)}</div>
          </div>
          <div className="bh-voice" style={{ fontSize: 13, fontStyle: "italic", color: "#c2b393" }}>bhoomee</div>
        </div>
      </div>
    </div>
  );
}

/* ─── ATLAS ─── */
function Atlas({ offerings, onShare }) {
  const places = [...new Set(offerings.map((o) => o.place))];
  return (
    <div className="bh-fade" style={{ position: "relative", minHeight: "100vh", background: "#1e1912" }}>
      <div style={{ padding: "18px 16px 0", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <span className="bh-voice" style={{ fontSize: 22, color: C.paper }}>Your Atlas</span>
        <span className="bh-k" style={{ color: "#b9ab92" }}>{offerings.length} offering{offerings.length === 1 ? "" : "s"} · {places.length} place{places.length === 1 ? "" : "s"}</span>
      </div>
      <div style={{ padding: "18px 16px 0", display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 9 }}>
        {offerings.map((o) => (
          <button key={o.key} onClick={() => onShare(o)} style={{ padding: 0, border: "none", aspectRatio: "4/5", borderRadius: 8, background: o.tint, position: "relative", overflow: "hidden", cursor: "pointer" }}>
            {o.photo ? <img alt="" src={o.photo} style={{ position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover" }} /> : null}
            <div style={{ position: "absolute", inset: 0, background: "rgba(0,0,0,.3)" }} />
            <div style={{ position: "absolute", left: 7, right: 7, bottom: 6, textAlign: "left" }}>
              {o.word ? <div className="bh-voice" style={{ fontSize: 12, fontStyle: "italic", color: "#fff" }}>{o.word}</div> : null}
              <div style={{ fontSize: 9, letterSpacing: ".08em", color: "rgba(255,255,255,.85)", textTransform: "uppercase", marginTop: 2 }}>{o.domain}</div>
            </div>
          </button>
        ))}
        {Array.from({ length: Math.max(0, 6 - offerings.length) }).map((_, i) => <div key={"e" + i} style={{ aspectRatio: "4/5", borderRadius: 8, border: "1px dashed #4a4033" }} />)}
      </div>
      <div style={{ position: "absolute", left: 14, right: 14, bottom: 16, background: "rgba(28,23,16,.66)", borderRadius: 18, padding: "14px 16px" }}>
        <div className="bh-voice" style={{ fontSize: 16, color: C.paper, fontStyle: "italic" }}>{offerings.length === 0 ? "Nothing gathered yet. Go and meet one thing." : "Tap any tile to share it. The portrait is growing."}</div>
      </div>
    </div>
  );
}

/* PLACES */
function Places({ activeId, onLocate, choose, onModes }) {
  return (
    <div className="bh-fade" style={{ minHeight: "100vh", padding: "20px 16px 0" }}>
      <div className="bh-voice" style={{ fontSize: 24 }}>Where are you?</div>
      <button className="bh-cta" style={{ marginTop: 14 }} onClick={onLocate}>Use my real location</button>
      <button className="bh-ghost" style={{ marginTop: 10 }} onClick={onModes}>Choose a mode</button>
      <div style={{ fontSize: 12, color: "#7d7461", marginTop: 18, marginBottom: 10 }}>...or wander a demo place. The engine writes every mission fresh from each coordinate, so it feels made for anyone, anywhere.</div>
      {DEMO_PLACES.map((p) => (
        <button key={p.id} onClick={() => choose(p.id)} style={{ width: "100%", textAlign: "left", background: p.id === activeId ? "#fffdf8" : "transparent", border: "1px solid " + (p.id === activeId ? C.dawn : C.ash), borderRadius: 14, padding: "13px 15px", marginBottom: 10, cursor: "pointer" }}>
          <div className="bh-voice" style={{ fontSize: 18, color: C.clay }}>{p.label}</div>
          <div style={{ fontSize: 12, color: "#7d7461", marginTop: 2 }}>{p.coords.lat.toFixed(2)}, {p.coords.lon.toFixed(2)} — {p.liveState.weather}</div>
        </button>
      ))}
    </div>
  );
}

/* TAB BAR */
function TabBar({ view, setView, hasPlace }) {
  const tabs = [
    { id: "home", label: "Hearth", d: "M3 11l9-8 9 8M6 10v10h12V10" },
    { id: "atlas", label: "Atlas", d: "M4 5l6-2 4 2 6-2v16l-6 2-4-2-6 2zM10 3v16M14 5v16" },
    { id: "modes", label: "Modes", d: "M4 7h16M4 12h16M4 17h16" },
    { id: "places", label: "Places", d: "M12 21s7-6.5 7-11a7 7 0 1 0-14 0c0 4.5 7 11 7 11z M12 10a2 2 0 100-4 2 2 0 000 4z" },
  ];
  return (
    <div style={{ position: "fixed", left: 0, right: 0, bottom: 0, display: "flex", justifyContent: "center", zIndex: 40 }}>
      <div style={{ width: "100%", maxWidth: 460, background: "rgba(244,237,225,0.94)", backdropFilter: "blur(12px)", WebkitBackdropFilter: "blur(12px)", borderTop: "1px solid " + C.ash, display: "flex", padding: "8px 8px calc(8px + env(safe-area-inset-bottom,0px))" }}>
        {tabs.map((t) => {
          const active = view === t.id || (t.id === "home" && ["mission", "offering", "sit", "sealed"].includes(view)) || (t.id === "modes" && ["pilgrimSetup", "companionSetup"].includes(view));
          const color = active ? "#8a5a2a" : "#9A968A";
          const disabled = !hasPlace && (t.id === "home" || t.id === "atlas");
          return (
            <button key={t.id} onClick={() => (disabled ? setView("places") : setView(t.id))} style={{ flex: 1, background: "transparent", border: "none", cursor: "pointer", display: "flex", flexDirection: "column", alignItems: "center", gap: 3, padding: "4px 0", opacity: disabled ? 0.5 : 1 }}>
              <svg width="22" height="22" viewBox="0 0 24 24" fill="none"><path d={t.d} stroke={color} strokeWidth="1.6" strokeLinejoin="round" strokeLinecap="round" /></svg>
              <span style={{ fontSize: 11, fontWeight: active ? 500 : 400, color, fontFamily: C.ui }}>{t.label}</span>
            </button>
          );
        })}
      </div>
    </div>
  );
}

/* canvas card composer */
function loadImg(src) { return new Promise((res, rej) => { const i = new Image(); i.crossOrigin = "anonymous"; i.onload = () => res(i); i.onerror = rej; i.src = src; }); }
function wrap(ctx, text, x, y, maxW, lh) {
  const words = (text || "").split(" ");
  let line = "", yy = y;
  for (const w of words) {
    const test = line ? line + " " + w : w;
    if (ctx.measureText(test).width > maxW && line) { ctx.fillText(line, x, yy); line = w; yy += lh; } else line = test;
  }
  if (line) ctx.fillText(line, x, yy);
  return yy;
}
async function composeCard(off) {
  const W = 1080, H = 1350, cv = document.createElement("canvas"); cv.width = W; cv.height = H;
  const ctx = cv.getContext("2d");
  try { if (document.fonts && document.fonts.ready) await document.fonts.ready; } catch (e) { /* ignore */ }
  const k = off.sky || "day";
  const graded = k === "night" ? "#2a3350" : k === "wet" ? "#5f7371" : (k === "dawn" || k === "evening") ? "#c98f4e" : "#6f9193";
  const photoH = 860;
  ctx.fillStyle = graded; ctx.fillRect(0, 0, W, photoH);
  if (off.photo) {
    try { const img = await loadImg(off.photo); const s = Math.max(W / img.width, photoH / img.height); const dw = img.width * s, dh = img.height * s; ctx.drawImage(img, (W - dw) / 2, (photoH - dh) / 2, dw, dh); } catch (e) { /* keep bg */ }
  }
  const g = ctx.createLinearGradient(0, photoH - 260, 0, photoH); g.addColorStop(0, "rgba(0,0,0,0)"); g.addColorStop(1, "rgba(0,0,0,0.3)"); ctx.fillStyle = g; ctx.fillRect(0, photoH - 260, W, 260);
  ctx.fillStyle = "#faf5ea"; ctx.fillRect(0, photoH, W, H - photoH);
  ctx.fillStyle = "#2a1c0a"; ctx.textBaseline = "top"; ctx.font = "300 52px 'Fraunces', Georgia, serif";
  const y = wrap(ctx, receiveLine(), 70, photoH + 46, W - 140, 62);
  if (off.word) { ctx.font = "italic 300 40px 'Fraunces', Georgia, serif"; ctx.fillStyle = off.tint || "#6E7A4F"; ctx.fillText("- " + off.word, 70, y + 74); }
  ctx.font = "500 24px 'Inter', system-ui, sans-serif"; ctx.fillStyle = "#8a5a2a"; ctx.fillText((off.domain || "").toUpperCase() + "  " + (off.arc || "").toUpperCase(), 70, H - 120);
  ctx.font = "400 24px 'Inter', system-ui, sans-serif"; ctx.fillStyle = "#a89a80"; ctx.fillText((off.place || "") + " - " + fmtDate(off.date), 70, H - 82);
  ctx.font = "italic 300 30px 'Fraunces', Georgia, serif"; ctx.fillStyle = "#c2b393"; ctx.textAlign = "right"; ctx.fillText("bhoomee", W - 60, H - 96); ctx.textAlign = "left";
  return await new Promise((res) => cv.toBlob((b) => res(b), "image/png", 0.92));
}

/* helpers */
function Pill({ children, dim }) { return <span style={{ fontSize: 10, letterSpacing: ".14em", textTransform: "uppercase", color: dim ? "#9a8f7c" : "#8a5a2a", border: "1px solid #d8c3a2", borderRadius: 999, padding: "4px 10px" }}>{children}</span>; }
function shorten(s) { if (!s) return ""; const p = s.split(". "); return p.length > 1 ? p[0] + "." : s; }
function arcStage(m) {
  const map = { notice: "Notice", understand: "Understand", document: "Document", contribute: "Contribute", tend: "Tend", trace: "Understand", measure: "Understand", gather: "Document", offer: "Contribute" };
  if (m && m.arcStage && map[m.arcStage]) return map[m.arcStage];
  if (m && m.id && /^(W3|Wa1|X2)/.test(m.id)) return "Contribute";
  if (m && m.id && /^(W2|N2|L2|Wa2)/.test(m.id)) return "Understand";
  if (m && m.id && /^(S2|A2)/.test(m.id)) return "Document";
  return "Notice";
}
function receiveLine() { return "You saw it. That's the exact thing I wanted you to meet."; }
function fmtDate(iso) { try { return new Date(iso).toLocaleDateString(undefined, { day: "numeric", month: "short" }); } catch (e) { return iso; } }
